// <auto-generated />
namespace ChristmasCoding.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Adding_Facebook_Users_Table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Adding_Facebook_Users_Table));
        
        string IMigrationMetadata.Id
        {
            get { return "201612290040269_Adding_Facebook_Users_Table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
